### ISSUE TITLE
运行catkin_make出现错误

### ISSUE THREAD

**Issue by jiayuQi** [kintzhao/slamwareAPP#1]
在Ubuntu16.04，ROS Kinetic下编译程序，src内程序为 slamware_sdk_linux-x86_64-gcc4.8/samples/moveandpathdemo/src下程序，catkin_make编译后错误为：
![default](https://user-images.githubusercontent.com/31614596/30017883-663a78ac-918d-11e7-91b8-855e69c20fb5.png)

该如何解决？

**Comment by jiayuQi** [comment]
![default](https://user-images.githubusercontent.com/31614596/30018553-f046212a-918f-11e7-847e-84266ca2413f.png)
![default](https://user-images.githubusercontent.com/31614596/30018576-0446337c-9190-11e7-907b-a44b0a8a3468.png)

**Comment by jiayuQi** [comment]
原因应该是c++11下的string（std::basic_string<char>）当作参数传入非c++11的思岚SDK库（std::string），请问有什么解决方法？

**Comment by jiayuQi** [comment]
![image](https://user-images.githubusercontent.com/31614596/30041602-e2d0720a-921d-11e7-88a9-48c0d191896f.png)

**Comment by kintzhao** [comment]
you can git commit --hard 95c97462aecae93f37bd49fcfcf46db22bf59196 . and modify your code by ref this. .
https://github.com/kintzhao/slamwareAPP/commit/95c97462aecae93f37bd49fcfcf46db22bf59196

**Comment by kintzhao** [comment]
If you just test  the code from slamware_sdk_linux-x86_64-gcc4.8/samples.  it is better by cmake and improve it by yourself.  if you test my repo slamwareApp,  by catkin_make and keep the raw commit . you shoud debug your code with your commit by yourslef.

**Comment by jiayuQi** [comment]
我测试了你的slamwareApp，SlamwareCorePlatform::connect(ip_addres_, 1445)出现问题：
undefined reference to `rpos::robot_platforms::SlamwareCorePlatform::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
ip_addres_的格式为std::__cxx11::basic_string c++11标准的，但是connect(const std::string& host, int port, int timeoutInMs = 10000)中的格式为std::string。
这个问题得怎么解决？可以提供一些建议吗？

**Comment by jiayuQi** [comment]
关闭C++11特性后
![image](https://user-images.githubusercontent.com/31614596/30051499-e337a75e-9254-11e7-8aba-4c9203da124a.png)
思岚SDK的问题解决了，但是又出现新的问题：ros的库都出现了未定义引用的错误
对‘ros::init(int&, char**, std::string const&, unsigned int)’未定义的引用
对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
对‘ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)’未定义的引用
......

**Comment by kintzhao** [comment]
你把你的代码传到你的github仓库， 我下下来试试看吧。。。


我在ubuntu14.04 + indigo  是正常的。。






<http://www.slamtec.com/>

________________________________
发件人: jiayuQi <notifications@github.com>
发送时间: 2017年9月5日 16:14:36
收件人: kintzhao/slamwareAPP
抄送: Kint Zhao; Comment
主题: Re: [kintzhao/slamwareAPP] 运行catkin_make出现错误 (#1)


关闭C++11特性后
[image]<https://user-images.githubusercontent.com/31614596/30051499-e337a75e-9254-11e7-8aba-4c9203da124a.png>
思岚SDK的问题解决了，但是又出现新的问题：ros的库都出现了未定义引用的错误
对‘ros::init(int&, char**, std::string const&, unsigned int)’未定义的引用
对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
对‘ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::lessstd::string, std::allocator<std::pair<std::string const, std::string> > > const&)’未定义的引用
......

―

**Comment by jiayuQi** [comment]
我就是把你的代码运行在了Ubuntu16.04+Kinetic上，其他没有做改变

**Comment by kintzhao** [comment]
I try it on ubuntu 16.04 and it still has error.   you should test it on ubuntu 14.04 (GCC 4.8)  at first,  I will try my best to solve this  problem  at my plan.
